### ISSUE TITLE
Repos:       <short description of the issue> @?

### ISSUE THREAD

**Issue by takanome-dev** [TAKANOME-DEV/test-action#22]
### Suggestion

N/a

**Comment by takanome-dev** [comment]
just testing something...

**Comment by takanome-dev** [comment]
Hey, can you please assign this issue to me?

**Comment by takanome-dev** [comment]
Round 2, can you please assign this issue to me?

**Comment by koppor** [comment]
Well, I would like to work on this issue, too!

**Comment by takanome-dev** [comment]
just need to resolve the conflicts and merge the pr 🚀
